Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.box_check_update = false

  # Config hardware for libvirt
  config.vm.provider "libvirt" do |lv|
    lv.memory = 1024
    lv.cpus = 1
  end

  # Machine 1: Server
  config.vm.define "thi-phngS" do |server|
    server.vm.hostname = "thi-phngS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provision "shell", path: "scripts/server.sh"
  end

  # Machine 2: Worker
  config.vm.define "thi-phngSW" do |worker|
    worker.vm.hostname = "thi-phngSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provision "shell", path: "scripts/worker.sh"
  end
end
